#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0

# {fact rule=cfn-custom-elb-acm-certificate@v1.0 defects=1}
Resources:
  Elb:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      AccessLoggingPolicy:
        Enabled: true
      # Noncompliant: Load Balancer doest not use HTTPS/SSL certificates provided by AWS Certificate Manager (ACM).
      Listeners:
        - Protocol: HTTPS
# {/fact}
