#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0

# {fact rule=cfn-custom-cloudfront-origin@v1.0 defects=1}
Resources:
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        ViewerCertificate:
          AcmCertificateArn: "cert-test"
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
        WebACLId: arn:aws:wafv2:us-east-1:123456789012:global/webacl/ExampleWebACL/12345
        Logging:
          Bucket: myawslogbucket.s3.amazonaws.com
        OriginGroups:
          Quantity: 1
          # Noncompliant: Origin Group does not contain two Origin Group Members.
          Items:
            - Members:
                Quantity: 0
# {/fact}
