#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0

# {fact rule=cfn-custom-efs-resources@v1.0 defects=1}
Resources:
  ExampleEfs:
    Type: AWS::EFS::FileSystem
    Properties:
      PerformanceMode: generalPurpose
      Encrypted: true
      # Noncompliant: `BackupPolicy` status is `DISABLED`.
      BackupPolicy:
        Status: 'DISABLED'
# {/fact}
