#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0

# {fact rule=cfn-custom-ec2-instance-profile-attached@v1.0 defects=1}
Resources:
  ExampleEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref pInstanceType
      # Noncompliant: No Iam profile attached with the instance.
      Monitoring: true
# {/fact}
